1-line install: facilitate testing w/ ad hoc PR's e.g. sudo iiab 2607

diff --git a/iiab b/iiab
--- a/iiab
+++ b/iiab
@@ -231,7 +231,43 @@ else
     git clone https://github.com/iiab/iiab-factory --depth 1
 fi
 
-# I. Install Ansible + 2 IIAB repos
+# I. Install optional PR's from iiab/iiab & iiab/iiab-admin-console
+echo -e "\n\nInstall any requested PR's e.g. 'sudo iiab 361 2604 2607'\n"
+$APTPATH/apt -y install jq    # UX delay is serious: try sed/awk instead?
+for pr in $*
+do
+    if (( pr >= 1561 )); then    # iiab/iiab's lowest PR as of October 2020
+        repo=iiab
+    else
+        repo=iiab-admin-console
+    fi
+
+    http_code=$(curl -sH "Accept: application/vnd.github.v3" https://api.github.com/repos/iiab/$repo/pulls/$pr -w "%{http_code}" -o /tmp/iiab-pr.json)
+    if [ "$http_code" != 200 ] ; then
+        echo -e "\n\e[41mCOULD NOT FIND PR #$pr (https://github.com/iiab/$repo/pull/$pr)\e[0m\n"
+        echo -e "\e[41mHTTP ERROR: $http_code\e[0m\e[1m\n"
+        [ "$http_code" = 403 ] && echo -e "403 errors can happen if you request 60+ PR's in one hour:\n"
+        cat /tmp/iiab-pr.json    # GitHub sometimes includes an English explanation of the error, and URL, e.g. https://developer.github.com/v3/#rate-limiting
+        echo
+        curl -IsH "Accept: application/vnd.github.v3" https://api.github.com/repos/iiab/$repo/pulls/$pr    # HTTP headers typically reveal a lot more!
+        echo -e "\e[7mTry Pull Requests (NUMBERS) from iiab/iiab or iiab/iiab-admin-console e.g.:\e[0m\n"
+        echo -e "   sudo iiab 361 2604 2607"
+        echo -e "   curl d.iiab.io/install.txt | sudo bash -s 361 2604 2607\n"
+        exit 1
+    fi
+
+    account=$(jq -r '.head.label' /tmp/iiab-pr.json | cut -d: -f1)
+    branch=$(jq -r '.head.label' /tmp/iiab-pr.json | cut -d: -f2)
+
+    echo -e "\nPR #$pr: cd /opt/iiab/$repo"
+    cd /opt/iiab/$repo
+    #git checkout -b POTLUCK master    # If a branch norm is desired in future?
+    echo -e "git pull https://github.com/$account/$repo $branch"    # Or $repo.git
+    git pull https://github.com/$account/$repo $branch || { echo -e "\ngit exit/error code: $?\n"; exit 1; }
+    echo "$pr $(date '+%F %T %Z')" >> /etc/iiab/pr-list    # For iiab-diagnostics
+done
+
+# J. Install Ansible + 2 IIAB repos
 echo -e "\n\nINSTALL ANSIBLE + CORE IIAB SOFTWARE + ADMIN CONSOLE / CONTENT PACK MENUS...\n"
 
 echo -e "Install Ansible..."
@@ -279,7 +315,7 @@ else
     systemctl start iiab-cmdsrv || true    # Overrides 'set -e'
 fi
 
-# J. KA Lite prep
+# K. KA Lite prep
 if [ -d /library/ka-lite ]; then
     echo -e "\n\nKA LITE REQUIRES 2 THINGS...\n"
 
@@ -319,7 +355,7 @@ fi
 # kalite manage retrievecontentpack download en
 # OLD WAY ABOVE - fails w/ sev ISPs per https://github.com/iiab/iiab/issues/871
 
-# K. Start BitTorrent downloads, e.g. if $CONFDIR/local_vars.yml requested any
+# L. Start BitTorrent downloads, e.g. if $CONFDIR/local_vars.yml requested any
 if (systemctl -q is-active transmission-daemon) then
     echo -e "\n\nSTARTING BITTORRENT DOWNLOAD(S) for KA Lite...Please Monitor: http://box:9091\n"
     transmission-remote -n Admin:changeme -t all --start
@@ -327,7 +363,7 @@ fi
 
 touch $FLAGDIR/iiab-complete
 
-# L. Educate Implementers prior to rebooting!
+# M. Educate Implementers prior to rebooting!
 echo -e "\n\n         ┌───────────────────────────────────────────────────────────┐"
 echo -e "         │                                                           │"
 echo -e "         │   INTERNET-IN-A-BOX (IIAB) SOFTWARE INSTALL IS COMPLETE   │"
