workaround pantry.learningequality.org issue iiab/iiab/#2538

diff --git a/iiab b/iiab
--- a/iiab
+++ b/iiab
@@ -251,24 +251,24 @@ if [ -d /library/ka-lite ]; then
         echo -e "$FLAGDIR/kalite-zone-complete\n"
     fi
 
-    echo -e "\nInstall KA Lite's mandatory 0.9 GB English Pack... (en.zip)\n"
-    if [ ! -f $FLAGDIR/kalite-en.zip-complete ]; then
+#    echo -e "\nInstall KA Lite's mandatory 0.9 GB English Pack... (en.zip)\n"
+#    if [ ! -f $FLAGDIR/kalite-en.zip-complete ]; then
         #echo -e 'Now retrieving it...\n'
-        cd /tmp
-        if [ -f en.zip ]; then
-            if [ $(wc -c < en.zip) -ne 929916955 ]; then
-                echo -e "\nERROR: /tmp/en.zip must be 929,916,955 bytes to proceed.\n" >&2
-                exit 1
-            else
-                echo -e "\nUsing existing /tmp/en.zip whose 929,916,955 byte size is correct!\n"
-            fi
-        else
-            wget http://pantry.learningequality.org/downloads/ka-lite/0.17/content/contentpacks/en.zip
-        fi
-        echo -e 'Now installing /tmp/en.zip into /library/ka-lite/content/*\n'
-        kalite manage retrievecontentpack local en en.zip
-        touch $FLAGDIR/kalite-en.zip-complete
-    fi
+#        cd /tmp
+#        if [ -f en.zip ]; then
+#            if [ $(wc -c < en.zip) -ne 929916955 ]; then
+#                echo -e "\nERROR: /tmp/en.zip must be 929,916,955 bytes to proceed.\n" >&2
+#                exit 1
+#            else
+#                echo -e "\nUsing existing /tmp/en.zip whose 929,916,955 byte size is correct!\n"
+#            fi
+#        else
+#            wget http://pantry.learningequality.org/downloads/ka-lite/0.17/content/contentpacks/en.zip
+#        fi
+#        echo -e 'Now installing /tmp/en.zip into /library/ka-lite/content/*\n'
+#        kalite manage retrievecontentpack local en en.zip
+#        touch $FLAGDIR/kalite-en.zip-complete
+#    fi
 fi
 # WARNING: /tmp/en.zip (and all stuff in /tmp) is auto-deleted during reboots
 # NEW WAY ABOVE - since 2018-07-03 - installs KA Lite's mandatory English Pack
@@ -277,12 +277,12 @@ fi
 # OLD WAY ABOVE - fails w/ sev ISPs per https://github.com/iiab/iiab/issues/871
 
 # K. Start BitTorrent downloads, e.g. if $CONFDIR/local_vars.yml requested any
-if (systemctl -q is-active transmission-daemon) then
-    echo -e "\n\nSTARTING BITTORRENT DOWNLOAD(S) for KA Lite...Please Monitor: http://box:9091\n"
-    transmission-remote -n Admin:changeme -t all --start
-fi
+#if (systemctl -q is-active transmission-daemon) then
+#    echo -e "\n\nSTARTING BITTORRENT DOWNLOAD(S) for KA Lite...Please Monitor: http://box:9091\n"
+#    transmission-remote -n Admin:changeme -t all --start
+#fi
 
-touch $FLAGDIR/iiab-complete
+#touch $FLAGDIR/iiab-complete
 
 # L. Educate Implementers prior to rebooting!
 echo -e "\n\n         ┌───────────────────────────────────────────────────────────┐"
