use flags in iiab-factory to mark progress

diff --git a/scripts/post-install b/scripts/post-install
--- a/scripts/post-install
+++ b/scripts/post-install
@@ -1,27 +1,37 @@
 #!/bin/bash -e
-
+FLAGS=$BASE/iiab-factory/flags
 # Rebuilds local library.xml in case ZIM files added to /library/zims/content
-iiab-make-kiwix-lib
-echo -e 'Now running kalite zone'
-# /usr/bin/kalite venv wrapper does this: export KALITE_HOME=/library/ka-lite
-kalite manage generate_zone || true    # Overrides "set -e" allowing repeat run
-# Register with KA Lite - just the anonymous registration
-
-echo -e 'Now retreiving kalite en.zip'
-# WARNING: /tmp/en.zip (and all stuff in /tmp) is auto-deleted during reboots
-cd /tmp/    # Or /opt/iiab/downloads or /library/downloads if you prefer
-if [ -f en.zip ]; then
-    if [ $(wc -c < en.zip) -ne 929916955 ]; then
-        echo -e "\nERROR: /tmp/en.zip must be 929,916,955 bytes to proceed.\n" >&2
-        exit 1
-    else
-	echo -e "\nUsing existing /tmp/en.zip whose 929,916,955 byte size is correct!\n"
-    fi
-else
-    wget http://pantry.learningequality.org/downloads/ka-lite/0.17/content/contentpacks/en.zip
+if [ ! -f $FLAGS/kiwix-lib-complete ]; then
+    echo -e 'Now running iiab-make-kiwix-lib'
+    iiab-make-kiwix-lib
+    touch $FLAGS/kiwix-lib-complete
 fi
-echo -e 'Now installing kalite en.zip'
-kalite manage retrievecontentpack local en en.zip
-# NEW WAY ABOVE - since 2018-07-03 - installs KA Lite's mandatory English Pack
-# kalite manage retrievecontentpack download en
-# OLD WAY ABOVE - fails w/ sev ISPs per https://github.com/iiab/iiab/issues/871
+
+# /usr/bin/kalite venv wrapper does this: export KALITE_HOME=/library/ka-lite
+# Register with KA Lite - just the anonymous registration
+if [ ! -f $FLAGS/kalite-zone-complete ]; then
+     echo -e 'Now running kalite zone'
+     kalite manage generate_zone
+     touch $FLAGS/kalite-zone-complete
+fi
+
+if [ ! -f $FLAGS/kalite-en.zip-complete ]; then
+    echo -e 'Now retreiving kalite en.zip'
+    cd /opt/iiab/downloads
+    if [ -f en.zip ]; then
+        if [ $(wc -c < en.zip) -ne 929916955 ]; then
+            echo -e "\nERROR: /opt/iiab/iiab/downloads/en.zip must be 929,916,955 bytes to proceed.\n" >&2
+            exit 1
+        else
+            echo -e "\nUsing existing /opt/iiab/iiab/downloads/en.zip whose 929,916,955 byte size is correct!\n"
+        fi
+    else
+        wget http://pantry.learningequality.org/downloads/ka-lite/0.17/content/contentpacks/en.zip
+    fi
+    echo -e 'Now installing kalite en.zip'
+    kalite manage retrievecontentpack local en en.zip
+    # NEW WAY ABOVE - since 2018-07-03 - installs KA Lite's mandatory English Pack
+    # kalite manage retrievecontentpack download en
+    # OLD WAY ABOVE - fails w/ sev ISPs per https://github.com/iiab/iiab/issues/871
+    touch $FLAGS/kalite-en.zip-complete
+fi
